# Generated by Django 3.2.9 on 2023-04-09 21:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0002_alter_operation_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="source_of_income",
        ),
        migrations.DeleteModel(
            name="SourceOfIncome",
        ),
    ]
