# Generated by Django 3.2.9 on 2023-04-09 21:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0005_category_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="operation",
            name="title",
        ),
        migrations.AddField(
            model_name="operation",
            name="comment",
            field=models.TextField(blank=True, null=True, verbose_name="Комментарий"),
        ),
    ]
