# Generated by Django 3.2.9 on 2023-04-10 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_alter_category_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
