# Generated by Django 3.2.9 on 2023-04-11 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0008_remove_category_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
    ]
