# Generated by Django 3.2.9 on 2023-04-16 12:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("finances", "0009_alter_operation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="operation",
            name="date",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
    ]
